apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: inno
data:
  SERVER_PORT: "8080"
  MONGODB_URI: "mongodb://payment-mongo:27017"
  MONGODB_DATABASE: "payment_service"
  AUTH_SERVICE_JWK_SET_URI: "http://auth-service:8080/.well-known/jwks.json"
  USER_SERVICE_URL: "http://user-service:8080"
  KAFKA_BOOTSTRAP_SERVERS: "payment-kafka:9092"
  PAYMENT_EVENTS_TOPIC: "payment-events"