apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: inno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: payment-service
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
          image: inno-payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payment-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6

