apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: inno
data:
  SERVER_PORT: "8080"
  SPRING_DATA_REDIS_HOST: "user-redis"
  SPRING_DATA_REDIS_PORT: "6379"
  AUTH_JWKS_URI: "http://auth-service:8080/.well-known/jwks.json"